spring.application.name=coreservice

server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8nuj1nlk1mc73a52r5g-a:5432/hvd_nmce
spring.datasource.username=hvd_nmce_user
spring.datasource.password=ZIpiSm4ozeFBaq1srxm078QmomnJQQTi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true